name: "Get kube namespace"
description: "Get kube namespace"
inputs:
outputs:
  namespace:
    value: ${{ steps.namespace.outputs.name }}
runs:
  using: "composite"
  steps:
    - name: Set branch name
      id: branch
      run: echo "::set-output name=name::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
    - name: Set namespace name
      id: namespace
      run: |
        yarn add @socialgouv/kosko-charts
        NAMESPACE=$(node -e "console.log(require('@socialgouv/kosko-charts/utils/environmentSlug').generate('${{ steps.branch.outputs.name }}'))")
        echo "::set-output name=name::$(echo ${NAMESPACE})"
    - name: Debug
      run: |
        echo ${{ steps.branch.outputs.name }}
        echo ${{ steps.namespace.outputs.name }}
