name: Env informations
description: Generate proper env names for usage in kubernetes
outputs:
  namespace:
    description: "Destination namespace"
    value: ${{ steps.env.outputs.namespace }}
  branch:
    description: "Destination branch"
    value: ${{ steps.env.outputs.branch }}
  project:
    description: "Destination project"
    value: ${{ steps.env.outputs.project }}

runs:
  using: "composite"
  steps:
    - name: Get environment
      id: env
      shell: bash
      run: |
        which env-slug || npm i -g @socialgouv/env-slug
        RAW_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        BRANCH=$(env-slug "${RAW_BRANCH}")
        PROJECT=${GITHUB_REPOSITORY##*/}
        NAMESPACE=$(env-slug "${PROJECT}-${RAW_BRANCH}")
        echo "namespace=$(echo ${NAMESPACE})" >> $GITHUB_OUTPUT
        echo "project=$(echo ${PROJECT})" >> $GITHUB_OUTPUT
        echo "branch=$(echo ${BRANCH})" >> $GITHUB_OUTPUT
