name: "🪞🔌🇫🇷"
description: "Mirror git to https://gitlab.fabrique.social.gouv.fr"
inputs:
  token:
    description: "Your token"
  project:
    description: "Where to sync to in your git remote"
  remote:
    required: false
    description: "The Git remote to push to"
    default: "gitlab.fabrique.social.gouv.fr"
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set ${{ inputs.remote }} remote
      shell: bash
      run: |
        git config --global user.name 'SocialGroovyBot'
        git config --global user.email 'contact@fabrique.social.gouv.fr'
        git remote add ${{ inputs.remote }} https://github:${{ inputs.token }}@${{ inputs.remote }}/${{ inputs.project }}.git
    - name: Push
      shell: bash
      run: |
        case "${{ github.event_name }}" in
        "push")
          echo "git push --force ${{ inputs.remote }} "${{ github.event.ref }}""
          git push --force ${{ inputs.remote }} "${{ github.event.ref }}"
          ;;
        "delete")
          echo "git push --force --delete ${{ inputs.remote }} ${{ github.event.ref }}"
          git push --force --delete ${{ inputs.remote }} "${{ github.event.ref }}"
          ;;
        *)
          echo "Unexpected event : ${{ github.event_name }}"
          exit 42
        esac
