name: "🪞🔌🇫🇷"
description: "Mirror git to https://gitlab.factory.social.gouv.fr"
inputs:
  project:
    description: "Where to sync to"
  gitlab-token:
    description: "Your gitlab token"
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set gitlab.factory.social.gouv.fr remote
      shell: bash
      run: |
        git config --global user.name 'SocialGroovyBot'
        git config --global user.email 'contact@fabrique.social.gouv.fr'
        git remote add gitlab.factory.social.gouv.fr https://github:${{ inputs.gitlab-token }}@gitlab.factory.social.gouv.fr/${{ inputs.project }}.git
    - name: Push
      shell: bash
      run: |
        case "${{ github.event_name }}" in
        "push")
          # Get the ref name
          # see https://stackoverflow.com/a/58034787
          echo "git push --force gitlab.factory.social.gouv.fr ${GITHUB_REF##*/}"
          git push --force gitlab.factory.social.gouv.fr "${GITHUB_REF##*/}"
          ;;
        "delete")
          echo "git push --force --delete gitlab.factory.social.gouv.fr ${{ github.event.ref }}"
          git push --force --delete gitlab.factory.social.gouv.fr "${{ github.event.ref }}"
          ;;
        *)
          echo "Unexpected event : ${{ github.event_name }}"
          exit 42
        esac
