name: Deactivate
description: "Delete review branch environment and database"
inputs:
  kube-config:
    description: "The base64 of the kubeconfig"
    required: true
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
  adminPgSecret:
    description: "PG Secret admin secretRefName"
    default: azure-pg-admin-user
    required: true
  rancherProjectName:
    description: "Rancher project name, used for ci namespace, default to repository name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # could be extracted in some external action
    - name: Get k8s infos
      id: k8s
      shell: bash
      run: |
        which env-slug || npm i -g @socialgouv/env-slug
        RAW_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        BRANCH=$(env-slug "${RAW_BRANCH}")
        PROJECT=${GITHUB_REPOSITORY##*/}
        NAMESPACE=$(env-slug "${PROJECT}-${RAW_BRANCH}")
        echo "namespace=$(echo ${NAMESPACE})" >> $GITHUB_OUTPUT
        echo "project=$(echo ${PROJECT})" >> $GITHUB_OUTPUT
        echo "branch=$(echo ${BRANCH})" >> $GITHUB_OUTPUT

    - name: Write kubeconfig
      uses: SocialGouv/actions/util-write-kubeconfig@v1
      with:
        kubeconfig: ${{ inputs.kube-config }}

    - name: Delete k8s environment
      shell: bash
      run: |
        echo "kubectl delete ns ${{ steps.k8s.outputs.namespace }}"
        kubectl delete ns ${{ steps.k8s.outputs.namespace }} || true
        echo "🪦"

    - name: Drop database
      uses: SocialGouv/actions/autodevops-drop-db@v1
      with:
        kubeconfig: ${{ inputs.kube-config }}
        adminPgSecret: ${{ inputs.adminPgSecret }}
        rancherProjectName: ${{ inputs.rancherProjectName }}

    - name: Get deployment from PR
      uses: maxgfr/github-multi-deployments@v1.3.2
      id: envs
      with:
        step: get-env
        token: ${{ inputs.github-token }}
        debug: true

    - name: Notify deployment deactivation
      uses: maxgfr/github-multi-deployments@v1.3.2
      with:
        step: deactivate-env
        token: ${{ inputs.github-token }}
        env: ${{ steps.envs.outputs.env }}
        debug: true
