name: Deactivate
description: "Delete review branch environment and database"
inputs:
  kube-config:
    description: "The base64 of the kubeconfig"
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        actionPath: ${{ github.action_path }}

    # could be extracted in some external action
    - name: Get k8s infos
      id: k8s
      shell: bash
      run: |
        RAW_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        BRANCH=$(npx @socialgouv/env-slug "${RAW_BRANCH}")
        PROJECT=${GITHUB_REPOSITORY##*/}
        NAMESPACE=$(npx @socialgouv/env-slug "${PROJECT}-${RAW_BRANCH}")
        echo "::set-output name=namespace::$(echo ${NAMESPACE})"
        echo "::set-output name=project::$(echo ${PROJECT})"
        echo "::set-output name=branch::$(echo ${BRANCH})"

    - name: Write kubeconfig
      uses: SocialGouv/actions/util-write-kubeconfig@v1
      with:
        kubeconfig: ${{ inputs.kube-config }}

    - name: Delete k8s environment
      shell: bash
      run: |
        echo "kubectl delete ns ${{ steps.k8s.outputs.namespace }}"
        kubectl delete ns ${{ steps.k8s.outputs.namespace }} || true
        echo "🪦"

    - name: Drop database
      shell: bash
      env:
        SOCIALGOUV_BASE_DOMAIN: some-domain # mandatory to trigger GitHub environment in kosko-charts
      run: |
        PROJECT=${GITHUB_REPOSITORY#*/}
        npx @socialgouv/azure-db drop --application ${PROJECT} --database autodevops_${{ steps.k8s.outputs.branch }} --user user_${{ steps.k8s.outputs.branch }} || true

    # new version
    # - name: Drop database
    #   uses: SocialGouv/actions/autodevops-drop-db@v1
    #   with:
    #     kubeconfig: ${{ inputs.kube-config }}
    #     rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
    #     adminPgSecret: pg-scaleway

    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        token: ${{ inputs.github-token }}
        env: dev
        desc: "Environment ${{ steps.k8s.outputs.namespace }} has been deactivated"
