name: "Setup env"
description: "Setup env vars"
inputs:
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  rancherProjectName:
    description: "The Rancher project name, usually secrets.RANCHER_PROJECT_NAME, usefull jobs that needs secrets or ci namespaces"
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    default: dev
  baseNamespace:
    description: "Override base namespace"
  
runs:
  using: "composite"
  steps:
    - name: Setup env vars
      shell: bash
      run: |
        ORIGINAL_VARS="`set -o posix ; set`";
        
        export ENVIRONMENT=${{ inputs.environment || env.ENVIRONMENT }}
        export RANCHER_PROJECT_ID=${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        export RANCHER_PROJECT_NAME=${{ inputs.rancherProjectName || env.RANCHER_PROJECT_NAME }}
        export BASE_NAMESPACE=${{ inputs.baseNamespace || env.BASE_NAMESPACE }}

        source $GITHUB_ACTION_PATH/env.sh
        
        # put newly defined env vars to GITHUB_ENV
        grep -vFe "$ORIGINAL_VARS" <<<"$(set -o posix ; set)" | grep -v ^ORIGINAL_VARS= >> $GITHUB_ENV
