name: "Setup env"
description: "Setup env vars"
inputs:
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    default: dev
  productionNamespace:
    description: "Override production namesapce"
  projectName:
    description: "Override project name"

runs:
  using: "composite"
  steps:
    - name: Setup env vars
      shell: bash
      run: |
        ENVIRONMENT=${{ inputs.environment || env.ENVIRONMENT }}
        if [ -n "${{ inputs.projectName }}" ]; then
          PROJECT_NAME=${{ inputs.projectName }}
        else
          PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        fi
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        BRANCH_NAME=${BRANCH_NAME#refs/tags/}
        BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
        RANCHER_PROJECT_ID=${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        JOB_NAMESPACE=${PROJECT_NAME}-ci
        if [ "$ENVIRONMENT" = "prod" ]; then
          if [ -n "${{ inputs.productionNamespace }}" ]; then
            NAMESPACE="${{ inputs.productionNamespace }}"
          else
            NAMESPACE=$PROJECT_NAME
          fi
        elif [ "$ENVIRONMENT" = "preprod" ]; then
          NAMESPACE=${PROJECT_NAME}-preprod
        else
          NAMESPACE=$(npx @socialgouv/env-slug "${PROJECT_NAME}-${BRANCH_NAME}")
        fi
        SECRETS_NAMESPACE="${PROJECT_NAME}-secret"
        AUTODEVOPS_PATH=/tmp/autodevops

        # general purpose env vars
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "BRANCH_SLUG=$BRANCH_SLUG" >> $GITHUB_ENV
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        echo "RANCHER_PROJECT_ID=$RANCHER_PROJECT_ID" >> $GITHUB_ENV
        echo "JOB_NAMESPACE=$JOB_NAMESPACE" >> $GITHUB_ENV
        echo "SECRETS_NAMESPACE=$SECRETS_NAMESPACE" >> $GITHUB_ENV
        echo "AUTODEVOPS_PATH=$AUTODEVOPS_PATH" >> $GITHUB_ENV