name: "Setup env"
description: "Setup env vars"
inputs:
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  rancherProjectName:
    description: "The Rancher project name, usually secrets.RANCHER_PROJECT_NAME"
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    default: dev
  productionNamespace:
    description: "Override production namesapce"
  projectName:
    description: "Override project name"

runs:
  using: "composite"
  steps:
    - name: Setup env vars
      shell: bash
      run: |
        ENVIRONMENT=${{ inputs.environment || env.ENVIRONMENT }}
        if [ -n "${{ inputs.projectName }}" ]; then
          PROJECT_NAME=${{ inputs.projectName }}
        else
          PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        fi
        
        if [ -n "$GITHUB_HEAD_REF" ]; then
          BRANCH_NAME=$GITHUB_HEAD_REF
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME#refs/tags/}
        fi

        BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
        RANCHER_PROJECT_ID=${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        RANCHER_PROJECT_NAME=${{ inputs.rancherProjectName || env.RANCHER_PROJECT_NAME }}
        if [ -n "${{ inputs.productionNamespace }}" ]; then
          PRODUCTION_NAMESPACE="${{ inputs.productionNamespace }}"
        else
          PRODUCTION_NAMESPACE=$PROJECT_NAME
        fi
        if [ "$ENVIRONMENT" = "prod" ]; then
          NAMESPACE=$PRODUCTION_NAMESPACE
        elif [ "$ENVIRONMENT" = "preprod" ]; then
          NAMESPACE=${PROJECT_NAME}-preprod
        else
          NAMESPACE=$(npx @socialgouv/env-slug "${PROJECT_NAME}-${BRANCH_NAME}")
        fi
        JOB_NAMESPACE=${RANCHER_PROJECT_NAME:-"$PROJECT_NAME"}-ci
        SECRETS_NAMESPACE="${RANCHER_PROJECT_NAME:-"$PROJECT_NAME"}-secret"

        AUTODEVOPS_PATH=/tmp/autodevops
        mkdir -p $AUTODEVOPS_PATH

        # general purpose env vars
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "BRANCH_SLUG=$BRANCH_SLUG" >> $GITHUB_ENV
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        echo "RANCHER_PROJECT_ID=$RANCHER_PROJECT_ID" >> $GITHUB_ENV
        echo "RANCHER_PROJECT_NAME=$RANCHER_PROJECT_NAME" >> $GITHUB_ENV
        echo "JOB_NAMESPACE=$JOB_NAMESPACE" >> $GITHUB_ENV
        echo "SECRETS_NAMESPACE=$SECRETS_NAMESPACE" >> $GITHUB_ENV
        echo "AUTODEVOPS_PATH=$AUTODEVOPS_PATH" >> $GITHUB_ENV