name: "Setup env"
description: "Setup env vars"

runs:
  using: "composite"
  steps:
    - name: Setup env vars
      shell: bash
      run: |
        PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        BRANCH_NAME=${BRANCH_NAME#refs/tags/}
        BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
        RANCHER_PROJECT_ID=${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        JOB_NAMESPACE=${PROJECT_NAME}-ci
        if [ "$SOCIALGOUV_PRODUCTION" ]; then
          if [ -n "$SOCIALGOUV_PRODUCTION_NAMESPACE" ]; then
            NAMESPACE=$SOCIALGOUV_PRODUCTION_NAMESPACE
          else
            NAMESPACE=$PROJECT_NAME
          fi
        elif [ "$SOCIALGOUV_PREPRODUCTION" ]; then
          NAMESPACE=${PROJECT_NAME}-preprod
        else
          NAMESPACE=$(npx @socialgouv/env-slug "${PROJECT_NAME}-${BRANCH_NAME}")
        fi
        SECRETS_NAMESPACE="${PROJECT_NAME}-secret"
        
        # general purpose env vars
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "BRANCH_SLUG=$BRANCH_SLUG" >> $GITHUB_ENV
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        echo "RANCHER_PROJECT_ID=$RANCHER_PROJECT_ID" >> $GITHUB_ENV
        echo "JOB_NAMESPACE=$JOB_NAMESPACE" >> $GITHUB_ENV
        echo "SECRETS_NAMESPACE=$SECRETS_NAMESPACE" >> $GITHUB_ENV