name: "Wait for k8s job to complete"
description: "Wait for k8s job to complete"
inputs:
  namespace:
    description: "The Kubernetes namespace"
  jobName:
    description: "The Kubernetes job name"

runs:
  using: "composite"
  steps:

    - name: Wait for job to complete
      shell: sh
      run: |
        JOB="job/${{ inputs.jobName }}"
        retval_complete=1
        retval_failed=1
        while [[ $retval_complete -ne 0 ]] && [[ $retval_failed -ne 0 ]]; do
          sleep 2
          output=$(timeout 2s kubectl -n ${{ inputs.namespace }} wait --for=condition=complete $JOB --timeout=0 2>&1)
          retval_complete=$?
          output=$(timeout 2s kubectl -n ${{ inputs.namespace }} wait --for=condition=failed $JOB --timeout=0 2>&1)
          retval_failed=$?
          wait
        done
        if [ $retval_failed -eq 0 ]; then
          echo "$JOB failed"
          exit 1
        else
          echo "$JOB complete"
        fi
