name: "🪦"
description: "Bury the review branch k8s environment"
inputs:
  kube-config:
    description: "The base64 of the kubeconfig"
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.5.1

    - name: Get branch, project and namespace names
      shell: bash
      run: |
        cat ".github/review.env" >> $GITHUB_ENV
        echo "branch=${GITHUB_REF_SLUG_URL}" >> $GITHUB_ENV
        echo "project=${GITHUB_REPOSITORY_NAME_PART_SLUG_URL}" >> $GITHUB_ENV
        echo "namespace=${GITHUB_REPOSITORY_NAME_PART_SLUG_URL}-${GITHUB_REF_SLUG_URL}" >> $GITHUB_ENV

    - name: Get branch, project and namespace names
      shell: bash
      run: |
        echo "branch : ${{ env.branch }}" 
        echo "project : ${{ env.project }}" 
        echo "namespace : ${{ env.namespace }}"

    - name: Install Kapp
      uses: vmware-tanzu/carvel-setup-action@v1
      with:
        only: kapp
        token: ${{ inputs.github-token }}

    - name: Debug kapp version
      shell: bash
      run: kapp --version

    - name: Create kubernetes config
      shell: bash
      run: |
        mkdir ~/.kube
        echo "${{ inputs.kube-config }}" | base64 -d > ~/.kube/config

    - name: Delete k8s environment
      shell: bash
      run: |
        echo "kapp delete --yes --namespace ${{ env.namespace }}"
        kapp delete --yes --app ${{ env.project }} --namespace ${{ env.namespace }}
        echo "🪦"

    - name: Mark environment as deactivated
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        env: ${{ env.branch }}
        token: ${{ inputs.github-token }}
        desc: "Environment ${{ env.namespace }} has been deactivated"
