name: "Setup node for an action"
description: "Setup node package, cache and path for an action"
inputs:
  actionPath:
    description: "calling action path's to setup"

runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles(github.action_path, '/yarn.lock') }}
  
    - name: Install global JS dependencies
      shell: bash
      run: yarn global add ts-node typescript

    - name: Install action JS dependencies
      shell: bash
      run: yarn --cwd ${{ inputs.actionPath }} install --prefer-offline

    - name: Setup PATH
      shell: bash
      run: |
        echo "${{ inputs.actionPath }}/node_modules/.bin" >> $GITHUB_PATH
