name: "Autodevops"
description: "SocialGouv automated deployment"
inputs:
  project:
    description: "The project name, usually the repository name"
  imageName:
    description: "The image registry path"
  dockerfile:
    description: "The docker file path"
  dockerbuildargs:
    description: "The docker build arguments"
  token:
    description: "The GHCR authentication token"
  kubeconfig:
    description: "The Kubernetes authentication config"
  environment:
    description: "The deployment environment (dev | preprod | prod)"
  productionNamespace:
    description: "Override production namesapce"
  rancherId:
    description: "The Rancher project ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
outputs:
  url:
    description: "Main URL extracted from kube manifests"
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: "composite"
  steps:

  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Enable Relative Github Actions
    uses: socialgouv/actions/util-enable-relative-gh-actions@v1
    with:
      actionPath: ${{ github.action_path }}

  - name: Use autodevops build and register
    uses: ./.socialgouv/actions/autodevops-build-register
    with:
      token: ${{ inputs.token }}
      project: ${{ inputs.project }}
      imageName: ${{ inputs.imageName }}
      dockerfile: ${{ inputs.dockerfile }}
      environment:  ${{ inputs.environment }}
      dockerbuildargs: ${{ inputs.dockerbuildargs }}

  - name: Use autodevops manifests generation
    uses: ./.socialgouv/actions/autodevops-manifests
    with:
      rancherId: ${{ inputs.rancherId }}
      environment: ${{ inputs.environment }}
      productionNamespace: ${{ inputs.productionNamespace }}
      socialgouvBaseDomain: ${{ inputs.socialgouvBaseDomain }}

  - name: Use autodevops deployment
    id: deploy
    uses: ./.socialgouv/actions/autodevops-deploy
    with:
      token: ${{ inputs.token }}
      rancherId: ${{ inputs.rancherId }}
      kubeconfig: ${{ inputs.kubeconfig }}
      environment: ${{ inputs.environment }}
