name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  actionRepository:
    description: "The action repository to clone"
    default: https://github.com/SocialGouv/actions.git
  actionPath:
    description: "The calling's action path, pass github.action_path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Relative Github Actions
      shell: bash
      run: |
        set -x
        ACTION_PATH=${{ inputs.actionPath }}
        if [ -z "$SOCIALGOUV_ACTIONS_BRANCH" ]; then
          SOCIALGOUV_ACTIONS_BRANCH=$ACTION_PATH
          SOCIALGOUV_ACTIONS_BRANCH=$(echo $SOCIALGOUV_ACTIONS_BRANCH | sed 's/.*\/_actions\///')
          SOCIALGOUV_ACTIONS_BRANCH=${SOCIALGOUV_ACTIONS_BRANCH#*/}
          SOCIALGOUV_ACTIONS_BRANCH=${SOCIALGOUV_ACTIONS_BRANCH#*/}
          SOCIALGOUV_ACTIONS_BRANCH=${SOCIALGOUV_ACTIONS_BRANCH%/*}
          echo "SOCIALGOUV_ACTIONS_BRANCH=$SOCIALGOUV_ACTIONS_BRANCH" >> $GITHUB_ENV
        fi

        ACTIONS_PATH=/tmp/.socialgouv/actions/$SOCIALGOUV_ACTIONS_BRANCH
        mkdir -p $ACTION_PATH
        ln -s $ACTIONS_PATH $GITHUB_WORKSPACE/.actions || true

        if [ -d "$ACTIONS_PATH/.git" ]; then
          cd $ACTIONS_PATH
          git fetch origin $SOCIALGOUV_ACTIONS_BRANCH
          git reset --hard origin/$SOCIALGOUV_ACTIONS_BRANCH
        else
          mkdir -p $ACTIONS_PATH
          git clone \
            --depth 1 \
            ${{ inputs.actionRepository }} \
            --branch $SOCIALGOUV_ACTIONS_BRANCH \
            --single-branch \
            $ACTIONS_PATH
        fi