name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  path:
    description: "The target link"
    default: .actions
    required: true
  actionRepository:
    description: "The action repository to clone"
    default: SocialGouv/actions
  actionPath:
    description: "The calling's action path, pass github.action_path"
    required: true
outputs:
  actionBranch:
    description: "Action branch"
    value: ${{ steps.get_action_branch.outputs.actionBranch }}

runs:
  using: "composite"
  steps:
    - name: Extract action branch
      shell: bash
      id: get_action_branch
      run: |
        ACTION_BRANCH=${{ inputs.actionPath }}
        ACTION_BRANCH=$(echo $ACTION_BRANCH | sed 's/.*\/_actions\///')
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH%/*}
        echo "::set-output name=actionBranch::$(echo ${ACTION_BRANCH})"

    - name: Link directory to parent
      shell: bash
      run: |
        ln -s $ACTIONS_PATH $GITHUB_WORKSPACE/${{ inputs.path }}

    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.actionRepository }}
        ref: ${{ steps.get_action_branch.outputs.actionBranch }}
        path: ${{ inputs.path }}
