name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  path:
    description: "The target action"
    default: socialgouv
    required: true
  actionRepository:
    description: "The action repository to clone"
    default: https://github.com/SocialGouv/actions.git
  actionPath:
    description: "The calling's action path, pass github.action_path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Relative Github Actions
      shell: bash
      run: |
        set -x
        ACTION_PATH=${{ inputs.actionPath }}
        if ! [[ "$ACTION_PATH" == *"/_actions/"* ]]; then
          # called from a nested action
          exit 0
        fi

        ACTION_BRANCH=$ACTION_PATH
        ACTION_BRANCH=$(echo $ACTION_BRANCH | sed 's/.*\/_actions\///')
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH%/*}

        ACTIONS_PATH=$GITHUB_WORKSPACE/../.actions/${{ inputs.path }}
        if [ -d "$ACTIONS_PATH/.git" ]; then
          cd $ACTIONS_PATH
          git fetch origin $ACTION_BRANCH
          # git checkout -b $ACTION_BRANCH origin/$ACTION_BRANCH
          git reset --hard origin/$ACTION_BRANCH
        else
          mkdir -p $ACTIONS_PATH
          git clone \
            --depth 1 \
            ${{ inputs.actionRepository }} \
            --branch $ACTION_BRANCH \
            --single-branch \
            $ACTIONS_PATH
        fi