name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  path:
    description: "The target link"
    default: .socialgouv/actions
    required: true
  actionPath:
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Relative Github Actions
      shell: bash
      run: |
        set -x
        ACTIONS_PATH=$GITHUB_WORKSPACE/${{ inputs.path }}
        if [ -d $ACTIONS_PATH ]; then
          exit 0
        fi
        mkdir -p $ACTIONS_PATH
        ACTION_BRANCH=$(basename "${{ inputs.actionPath }}")
        git clone \
          --depth 1 \
          --branch $ACTION_BRANCH \
          --single-branch \
          $ACTIONS_PATH