name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  actionPath:
    description: "The calling's action path"
    required: true
  path:
    description: "The target link"
    default: .socialgouv/actions
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Relative Github Actions
      shell: bash
      run: ln -s ${{ inputs.actionPath }}/.. $GITHUB_WORKSPACE/${{ inputs.path }} || true