name: "Enable Relative Github Actions"
description: "Enable Relative Github Actions"
inputs:
  path:
    description: "The target link"
    default: .socialgouv/actions
    required: true
  actionRepository:
    description: "The action repository to clone"
    default: https://github.com/SocialGouv/actions
  actionPath:
    description: "The calling's action path, pass github.action_path"
    required: true
outputs:
  actionBranch:
    description: "Action branch"
    value: ${{ steps.get_action_branch.outputs.actionBranch }}

runs:
  using: "composite"
  steps:
    - name: Extract action branch
      shell: bash
      id: get_action_branch
      run: |
        set -x
        ACTIONS_PATH=$GITHUB_WORKSPACE/${{ inputs.path }}
        mkdir -p $ACTIONS_PATH
        
        # extract action branch from action path
        ACTION_BRANCH=${{ inputs.actionPath }}
        ACTION_BRANCH=$(echo $ACTION_BRANCH | sed 's/.*\/_actions\///')
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH#*/}
        ACTION_BRANCH=${ACTION_BRANCH%/*}

        echo "::set-output name=actionBranch::$(echo ${ACTION_BRANCH})"


    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.actionRepository }}
        ref: ${{ steps.get_action_branch.outputs.actionBranch }}