apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    component: {{ .Values.component }}
    application: {{ .Values.application }}
  name: {{ .Values.component }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: 0 * * * *
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ .Values.component }}-job
          namespace: {{ .Values.namespace }}
          labels:
            component: {{ .Values.component }}
            application: {{ .Values.application }}
        spec:
          restartPolicy: OnFailure
          concurrencyPolicy: Forbid
          containers:
            - name: {{ .Values.component }}-container
              image: node:14-alpine
              command:
                - sh
                - '-c'
                - npx @socialgouv/matomo-metabase
              envFrom:
                - secretRef:
                    name: cronjob-{{ .Values.component }}
              env:
                - name: STARTDATE
                  value: '2019-01-01'
                - name: DEBUG
                  value: '*'
