name: "Review Branch"
description: "Deploy a review branch"
inputs:
  project:
    description: "The project name, usually the repository name"
  imageName:
    description: "The image registry path"
  dockerfile:
    description: "The docker file path"
  token:
    description: "The GHCR authentication token"
  kubeconfig:
    description: "The Kubernetes authentication config"

runs:
  using: "composite"
  steps:

  - name: Use autodevops build and register
    uses: SocialGouv/actions/autodevops-build-register@master
    with:
      token: ${{ inputs.token }}
      project: ${{ inputs.project }}
      imageName: ${{ inputs.imageName }}
      dockerfile: ${{ inputs.dockerfile || './Dockerfile' }}

  - name: Use autodevops manifests generation
    uses: SocialGouv/actions/autodevops-manifests@master
    with:
      environment: "dev"

  - name: Use autodevops deployment
    uses: SocialGouv/actions/autodevops-deploy@master
    with:
      environment: "dev"
      token: ${{ inputs.token }}
      kubeconfig: ${{ inputs.kubeconfig }}
