name: "Generate manifests"
description: "Generate create database secret manifests based on k8s config folder"
inputs:
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"

runs:
  using: "composite"
  steps:

  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      submodules: recursive

  - name: Load environment variables
    shell: bash
    run: |
      if test -f ".github/dev.env"; then
        cat ".github/dev.env" >> $GITHUB_ENV
      fi

  - name: Yarn cache setup
    uses: c-hive/gha-yarn-cache@v2
    with:
      directory: .k8s

  - name: Install kosko-charts dependencies
    shell: bash
    run: yarn --cwd .k8s install --frozen-lockfile --prefer-offline

  - name: Generate k8s namespace
    shell: bash
    run: yarn --cwd .k8s --silent generate --env dev _namespace > namespace-dev.yml
    env:
      RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
      SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}

  - name: Generate create-db-secret job manifest
    shell: bash
    run: yarn --cwd .k8s --silent generate --env dev jobs/create-db-secret > create-db-secret.yml
    env:
      RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
      SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}

  - name: Archive create-db-secret job
    uses: actions/upload-artifact@v2
    with:
      name: create-db-secret.yml
      path: create-db-secret.yml

  - name: Get namespace name
    uses: mikefarah/yq@v4.13.4
    id: namespace
    with:
      cmd: yq eval '.metadata.name' namespace-dev.yml

  - name: Create kubernetes config
    shell: bash
    run: |
      mkdir ~/.kube
      touch ~/.kube/config
      echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config

  - name: Create db secret if not exists
    shell: bash
    run: |
      kubectl delete -f create-db-secret.yml --namespace ${{ steps.namespace.outputs.result }} || true
      kubectl apply -f create-db-secret.yml --namespace ${{ steps.namespace.outputs.result }}
