name: "Get application namespace"

description: "Get application namespace based on k8s manifest"

inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"

outputs:
  value:
    description: "Namespace value"
    value: ${{ steps.namespace.outputs.result }}

runs:
  using: "composite"
  steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load environment variables
        shell: bash
        run: |
          if test -f ".github/${{ inputs.environment }}.env"; then
            cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV
          fi

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: .k8s

      - name: Install kosko-charts dependencies
        shell: bash
        run: yarn --cwd .k8s install --frozen-lockfile --prefer-offline

      - name: Generate k8s namespace
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} _namespace > namespace-${{ inputs.environment }}.yml
        env:
          RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
          SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
          SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}
          SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}

      - name: Get namespace name
        uses: mikefarah/yq@v4.13.4
        id: namespace
        with:
          cmd: yq eval '.metadata.name' namespace-${{ inputs.environment }}.yml
