name: "Get application namespace"
description: "Get application namespace based on k8s manifest"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
outputs:
  value:
    description: "Namespace value"
    value: ${{ steps.namespace.outputs.value }}

runs:
  using: "composite"
  steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load environment variables
        shell: bash
        run: |
          cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: .k8s

      - name: Install kosko-charts dependencies
        shell: bash
        run: yarn --cwd .k8s install --frozen-lockfile --prefer-offline

      - name: Generate k8s namespace
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} _namespace > namespace-${{ inputs.environment }}.yml
        env:
          RANCHER_PROJECT_ID: ${{ env.RANCHER_PROJECT_ID }}
          SOCIALGOUV_BASE_DOMAIN: ${{ env.SOCIALGOUV_BASE_DOMAIN }}
          SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
          SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

      - name: Get namespace name
        uses: mikefarah/yq@master
        id: namespace
        with:
          cmd: |
            NAMESPACE=$(yq eval '.metadata.name' namespace-${{ inputs.environment }}.yml)
            echo NAMESPACE $NAMESPACE
            echo "::set-output name=value::$NAMESPACE"
