namespace: 
host: 
registry:
imageTag: 
ttl: 
rancherProjectId: my-cluser-id:my-project-id
gitBranch: my-awesome-branch
isProduction: false
isPreProduction: false
containerPort: 8080
envSecretName: 
envConfigName: 