name: "Generate manifests"
description: "Generate k8s manifests via kosko-charts autodevops"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
  productionNamespace:
    description: "Override production namesapce"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v1

    - name: Install kosko-charts autodevops
      shell: bash
      run: |
        npx degit SocialGouv/kosko-charts/templates/autodevops /tmp/autodevops
        rm -rf /tmp/autodevops/environments
        yarn --cwd /tmp/autodevops

    - name: Copy application k8s config to autodevops
      shell: bash
      run: |
        if [ -d ".socialgouv/environments" ]; then
          echo "$ cp -r .socialgouv/environments /tmp/autodevops/environments"
          cp -r .socialgouv/environments /tmp/autodevops/environments
        fi
        echo "$ cp .socialgouv/config.json /tmp/autodevops/"
        cp .socialgouv/config.json /tmp/autodevops/

    - name: Generate k8s namespace
      shell: bash
      run: |
        yarn --cwd /tmp/autodevops --silent generate --env ${ENVIRONMENT} _namespace > namespace-${ENVIRONMENT}.yml
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherId }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain }}
        SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}
        SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
        SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

    - name: Generate k8s manifests
      shell: bash
      run: |
        echo SOCIALGOUV_BASE_DOMAIN: $SOCIALGOUV_BASE_DOMAIN
        yarn --cwd /tmp/autodevops --silent generate --env ${ENVIRONMENT} > manifests-${ENVIRONMENT}.yml
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherId }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain }}
        SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}
        SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
        SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

    - name: Archive k8s namespace
      uses: actions/upload-artifact@v2
      with:
        name: namespace-${{ inputs.environment }}.yml
        path: namespace-${{ inputs.environment }}.yml

    - name: Archive k8s manifests
      uses: actions/upload-artifact@v2
      with:
        name: manifests-${{ inputs.environment }}.yml
        path: manifests-${{ inputs.environment }}.yml
