name: "Generate manifests"
description: "Generate k8s manifests via kosko-charts autodevops"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    required: true
  productionNamespace:
    description: "Override production namesapce"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load environment variables
      shell: bash
      run: |
        if test -f ".github/${{ inputs.environment }}.env"; then
          cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV
        fi

    - name: Degit autodevops template
      shell: bash
      run: |
        npx degit SocialGouv/kosko-charts/templates/autodevops /tmp/autodevops
        rm -rf /tmp/autodevops/environments

    - name: Copy application k8s config to autodevops
      shell: bash
      run: |
        DEST="/tmp/autodevops"
        if [ -d ".socialgouv/environments" ]; then
          echo "$ cp -r .socialgouv/environments $DEST/environments"
          cp -r .socialgouv/environments $DEST/environments
        fi
        if [ -d ".socialgouv/components" ]; then
          # use userland components instead of autodevops ones
          echo "$ rm -rf $DEST/components;"
          rm -rf $DEST/components
          echo "$ cp -r .socialgouv/* $DEST/"
          cp -r .socialgouv/* $DEST/
        fi
        if [ -f ".socialgouv/config.json" ]; then
          echo "$ cp .socialgouv/config.json $DEST/"
          cp .socialgouv/config.json $DEST/
        fi
        if [ -f ".socialgouv/kosko.toml" ]; then
          echo "$ cp .socialgouv/kosko.toml $DEST/"
          cp .socialgouv/kosko.toml $DEST/
        fi

    - name: Install dependencies
      shell: bash
      run: |
        yarn --cwd /tmp/autodevops

    # For example
    - name: Run kosko manifests tests
      shell: bash
      run: |
        if [ -f ".socialgouv/__tests__" ]; then
          yarn --cwd /tmp/autodevops test
        fi

    - name: Generate k8s namespace
      shell: bash
      run: |
        yarn --cwd /tmp/autodevops --silent generate --env ${ENVIRONMENT} _namespace > namespace-${ENVIRONMENT}.yml
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
        SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}
        SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
        SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

    - name: Generate k8s manifests
      shell: bash
      run: |
        echo SOCIALGOUV_BASE_DOMAIN: $SOCIALGOUV_BASE_DOMAIN
        yarn --cwd /tmp/autodevops --silent generate --env ${ENVIRONMENT} > manifests-${ENVIRONMENT}.yml
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
        SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}
        SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
        SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

    - name: Archive k8s namespace
      uses: actions/upload-artifact@v2
      with:
        name: namespace-${{ inputs.environment }}.yml
        path: namespace-${{ inputs.environment }}.yml

    - name: Archive k8s manifests
      uses: actions/upload-artifact@v2
      with:
        name: manifests-${{ inputs.environment }}.yml
        path: manifests-${{ inputs.environment }}.yml
