name: "⛑ Debug manifests ⛑"
description: "Debug some kubernetes manifests"
inputs:
  path:
    description: "Your manifests YAML file path"
  token:
    description: "Github token for PR comment"
outputs:
  json:
    description: "Json debug"
    value: ${{ steps.debug-manifests.outputs.json }}
  markdown:
    description: "Markdown debug"
    value: ${{ steps.debug-manifests.outputs.markdown }}
  text:
    description: "Text debug"
    value: ${{ steps.debug-manifests.outputs.text }}
runs:
  using: "composite"
  steps:
    - name: Debug manifests
      shell: bash
      id: debug-manifests
      run: |
        JSON=$(cat "${MANIFESTS}" | npx @socialgouv/parse-manifests --json)
        MARKDOWN=$(cat "${MANIFESTS}" | npx @socialgouv/parse-manifests --markdown)
        TEXT=$(cat "${MANIFESTS}" | npx @socialgouv/parse-manifests --text)

        echo "${TEXT}"

        JSON="${JSON//$'\r'/'%0D'}"
        MARKDOWN="${MARKDOWN//$'\r'/'%0D'}"
        TEXT="${TEXT//$'\r'/'%0D'}"

        echo "json=$JSON" >> $GITHUB_OUTPUT
        echo "markdown=$MARKDOWN" >> $GITHUB_OUTPUT
        echo "text=$TEXT" >> $GITHUB_OUTPUT
      env:
        MANIFESTS: ${{ inputs.path }}

    # necessary to find the PR on push events
    - uses: jwalton/gh-find-current-pr@v1
      id: finder

    - name: ⛑ Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        recreate: true
        message: |
          🎉 Deployment for commit ${{ github.sha }} :
          ${{ steps.debug-manifests.outputs.markdown }}
        GITHUB_TOKEN: ${{ inputs.token }}
