name: "⛑ Debug manifests ⛑"
description: "Debug some kubernetes manifests"
inputs:
  path:
    description: "Your manifests YAML file path"
  token:
    description: "Github token for PR comment"
  # env:
  #   description: "Env for the parse-manifests phase"
outputs:
  markdown:
    description: "Markdown debug"
    value: ${{ steps.debug-manifests.outputs.markdown }}
runs:
  using: "composite"
  steps:
    - name: Debug manifests
      shell: bash
      id: debug-manifests
      run: |
        cat "${MANIFESTS}"
        TEXT=$(cat "${MANIFESTS}" | npx @socialgouv/parse-manifests --text)
        echo "${TEXT}"
        MARKDOWN=$(cat "${MANIFESTS}" | npx @socialgouv/parse-manifests --markdown)
        MARKDOWN="${MARKDOWN//$'\n'/'%0A'}"
        MARKDOWN="${MARKDOWN//$'\r'/'%0D'}"
        echo "::set-output name=markdown::$MARKDOWN"
      env:
        MANIFESTS: ${{ inputs.path }}

    # necessary to find the PR on push events
    - uses: jwalton/gh-find-current-pr@v1
      id: finder

    - name: ⛑ Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: |
          Deployment ${{ github.sha }}.
          ${{ steps.debug-manifests.outputs.markdown }}
        GITHUB_TOKEN: ${{ inputs.token }}
