author: SocialGouv
name: Organization packages cleaner
description: Purge packages versions list
inputs:
  token:
    required: true
    default: ${{ github.token }}
    description: Personal access token (PAT) used to perform Github API requests
  retention-weeks:
    default: '2'
    required: true
    description: 'Number of weeks of retention preventing packages from being deleted'
  containers:
    default: ''
    required: true
    description: 'List of container packages to clean up'
runs:
  using: 'node12'
  main: 'dist/index.js'
