global:
  isProduction: false
  namespace: default
  repositoryName: the-awesome
  host:
  certSecretName: wildcard-crt
  branchSlug:
  image:
  imageTag:

components:
  app: true
  hasura: false
  maildev: false
  pgweb: false
  jobs: false

app: {}
hasura: {}
maildev: {}
pgweb: {}
jobs: {}