name: "Generate manifests"
description: "Generate restore manifests based on k8s config folder"
inputs:
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
  productionNamespace:
    description: "Override base project name"
  pgUserSecretPrefix:
    description: "Prefix for pg-user secret name, oldly azure-pg-user, in future pg-user"
    default: azure-pg-user
  jobNamespace:
    description: "Namespace where to run the job"
runs:
  using: "composite"
  steps:

  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Load environment variables
    shell: bash
    id: env
    run: |
      if test -f ".github/dev.env"; then
        cat ".github/dev.env" >> $GITHUB_ENV
      fi
      if [ -d ".k8s" ]; then K8S_FOLDER=".k8s"; fi
      if [ -d ".socialgouv" ]; then K8S_FOLDER=".socialgouv"; fi
      echo $K8S_FOLDER
      echo "K8S_FOLDER=$K8S_FOLDER" >> $GITHUB_OUTPUT

  - name: Yarn cache setup
    uses: c-hive/gha-yarn-cache@v2
    with:
      directory: ${{ steps.env.outputs.K8S_FOLDER }}

  - name: Install kosko-charts dependencies
    shell: bash
    run: yarn --cwd ${{ steps.env.outputs.K8S_FOLDER }} install --frozen-lockfile --prefer-offline

  - name: Generate k8s namespace
    shell: bash
    run: yarn --cwd ${{ steps.env.outputs.K8S_FOLDER }} --silent generate --env dev _namespace > namespace-dev.yml
    env:
      RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
      SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
      SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}

  - name: Generate restore-db job manifest
    shell: bash
    run: yarn --cwd ${{ steps.env.outputs.K8S_FOLDER }} --silent generate --env dev jobs/restore > restore-db.yml
    env:
      RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
      SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
      SOCIALGOUV_PRODUCTION_NAMESPACE: ${{ inputs.productionNamespace }}
      PG_USER_SECRET_PREFIX: ${{ inputs.pgUserSecretPrefix }}
      
  - name: Archive restore-db job
    uses: actions/upload-artifact@v2
    with:
      name: restore-db.yml
      path: restore-db.yml

  - name: Get namespace name
    uses: mikefarah/yq@v4.13.4
    id: namespace
    with:
      cmd: yq eval '.metadata.name' namespace-dev.yml

  - name: Create kubernetes config
    shell: bash
    run: |
      mkdir ~/.kube
      touch ~/.kube/config
      echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config

  - name: Seed database
    shell: bash
    run: |
      kubectl delete -f restore-db.yml --namespace ${{ inputs.jobNamespace || steps.namespace.outputs.result }} || true
      kubectl apply -f restore-db.yml --namespace ${{ inputs.jobNamespace || steps.namespace.outputs.result }}
