name: "Create database"
description: "Create database and user using random secure"
inputs:
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
  environment:
    description: "The deployment environment (dev | preprod | prod)"

runs:
  using: "composite"
  steps:
    # - name: Create DB secret
    #   uses: socialgouv/actions/autodevops-create-db-secret@v1
    #   with:
    #     kubeconfig: ${{ inputs.kubeconfig }}
    #     rancherId: ${{ inputs.rancherId }}
    #     socialgouvBaseDomain: ${{ inputs.socialgouvBaseDomain }}
    #     environment: ${{ inputs.environment }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get project and namespace names
      shell: bash
      run: |
        if test -f ".github/dev.env"; then
          cat ".github/dev.env" >> $GITHUB_ENV
        fi

    - name: Install kosko-charts autodevops
      shell: bash
      run: |
        rm -rf /tmp/autodevops
        npx degit SocialGouv/kosko-charts/templates/autodevops /tmp/autodevops
        yarn --cwd /tmp/autodevops

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: /tmp/autodevops


    - name: Generate k8s namespace
      shell: bash
      run: |
        yarn --cwd /tmp/autodevops --silent generate --env dev _namespace > namespace-${ENVIRONMENT}.yml
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}

    - name: Get namespace name
      uses: mikefarah/yq@v4.13.4
      id: namespace
      with:
        cmd: yq eval '.metadata.name' namespace-${{ inputs.environment }}.yml

    - name: Generate create-db manifests
      shell: bash
      run: yarn --cwd /tmp/autodevops --silent generate --env dev jobs/create-db > create-db.yml
      env:
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}

    - name: Archive create-db manifests
      uses: actions/upload-artifact@v2
      with:
        name: create-db.yml
        path: create-db.yml

    - name: Create kubernetes config
      shell: bash
      run: |
        mkdir -p ~/.kube
        touch ~/.kube/config
        echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config

    - name: Create secret if not exists
      shell: bash
      run: |
        K8S_NS=${{ steps.namespace.outputs.result }}
        PGPASSWORD_SECRET_NAME=pgpassword
        if [ -n "$(kubectl -n $K8S_NS get secret $PGPASSWORD_SECRET_NAME 2>/dev/null)" ]; then
          echo "PGPASSWORD secret named '$PGPASSWORD_SECRET_NAME' already exists in namespace '$K8S_NS'"
          exit 0
        fi
        PGPASSWORD=$(openssl rand -base64 32 | sed "s/[^[:alnum:]-]//g")
        kubectl -n $K8S_NS create secret generic $PGPASSWORD_SECRET_NAME --from-literal=PGPASSWORD=$PGPASSWORD
        echo "PGPASSWORD secret named '$PGPASSWORD_SECRET_NAME' created in namespace '$K8S_NS'"

    - name: Create database and user
      shell: bash
      run: |
        kubectl delete --namespace=${{ steps.namespace.outputs.result }} job/create-db-user || true
        kubectl apply --namespace=${{ steps.namespace.outputs.result }} -f create-db.yml

    - name: Wait for job to complete
      shell: sh
      run: |
        JOB="job/create-db"
        retval_complete=1
        retval_failed=1
        while [[ $retval_complete -ne 0 ]] && [[ $retval_failed -ne 0 ]]; do
          sleep 2
          output=$(timeout 2s kubectl -n ${{ steps.namespace.outputs.result }} wait --for=condition=complete $JOB --timeout=0 2>&1)
          retval_complete=$?
          output=$(timeout 2s kubectl -n ${{ steps.namespace.outputs.result }} wait --for=condition=failed $JOB --timeout=0 2>&1)
          retval_failed=$?
          wait
        done
        if [ $retval_failed -eq 0 ]; then
          echo "$JOB failed"
          exit 1
        else
          echo "$JOB complete"
        fi

    # - name: Wait for job to complete
    #   uses: SocialGouv/actions/autodevops-wait-job@devthejo/create-db
    #   with:
    #     namespace: ${{ steps.namespace.outputs.result }}
    #     jobName: create-db


