root: true
extends: 
  - "plugin:@typescript-eslint/all"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:prettier/recommended"
  - "eslint:recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  project:
    - tsconfig.json
  sourceType: "module"
env:
  node: true
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  "@typescript-eslint/no-magic-numbers": off
  "@typescript-eslint/strict-boolean-expressions": off
  "@typescript-eslint/prefer-nullish-coalescing": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/no-unsafe-call": off
  "@typescript-eslint/no-unsafe-member-access": off