apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjob-{{ .Values.component }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- tpl (.Values.cronjobSealedSecrets | toYaml) . | nindent 4 }}
  template:
    metadata:
      name: cronjob-{{ .Values.component }}
    type: Opaque
