name: "Generate manifests"
description: "Generate k8s manifests based on .k8s folder"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    required: true
  rancherId:
    description: "Rancher ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain: 
    description: "Base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
runs:
  using: "composite"
  steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load review environment variables
        shell: bash
        run: |
          if test -f ".github/${{ inputs.environment }}.env"; then
            cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV
          fi

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: .k8s

      - name: Install kosko-charts dependencies
        shell: bash
        run: yarn --cwd .k8s install --frozen-lockfile --prefer-offline

      - name: Generate k8s manifests
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} > manifests-${{ inputs.environment }}.yml
        env:
          RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
          SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
          SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
          SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

      - name: Generate k8s namespace
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} _namespace > namespace-${{ inputs.environment }}.yml
        env:
          RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
          SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
          SOCIALGOUV_PRODUCTION: ${{ inputs.environment == 'prod' && true || '' }}
          SOCIALGOUV_PREPRODUCTION: ${{ inputs.environment == 'preprod' && true || '' }}

      - name: Archive k8s manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests-${{ inputs.environment }}.yml
          path: manifests-${{ inputs.environment }}.yml

      - name: Archive k8s namespace
        uses: actions/upload-artifact@v2
        with:
          name: namespace-${{ inputs.environment }}.yml
          path: namespace-${{ inputs.environment }}.yml
