name: "Generate manifests"
description: "Generate k8s manifests based on .k8s folder"
inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"

runs:
  using: "composite"
  steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load review environment variables
        shell: bash
        run: |
          cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v2

      - name: Install kosko-charts dependencies
        shell: bash
        run: yarn --cwd .k8s install --frozen-lockfile --prefer-offline

      - name: Generate k8s manifests
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} > manifests-${{ inputs.environment }}.yml
        env:
          SOCIALGOUV_BASE_DOMAIN: ${{ env.SOCIALGOUV_BASE_DOMAIN }}

      - name: Generate k8s namespace
        shell: bash
        run: yarn --cwd .k8s --silent generate --env ${{ inputs.environment }} _namespace > namespace-${{ inputs.environment }}.yml
        env:
          SOCIALGOUV_BASE_DOMAIN: ${{ env.SOCIALGOUV_BASE_DOMAIN }}

      - name: Archive k8s manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests-${{ inputs.environment }}.yml
          path: manifests-${{ inputs.environment }}.yml

      - name: Archive k8s namespace
        uses: actions/upload-artifact@v2
        with:
          name: namespace-${{ inputs.environment }}.yml
          path: namespace-${{ inputs.environment }}.yml
