name: "Deploy"
description: "Deploy over Kubernetes"

inputs:
  environment:
    description: "The deployment environment (dev | preprod | prod)"
    required: true
  kubeconfig:
    description: "The Kubernetes authentication configuration"
    required: true
  token:
    description: "The Github authentication token"
    required: true
  rancherId:
    description: "The Rancher project ID"
    required: true
outputs:
  url:
    description: "Main URL extracted from kube manifests"
    value: ${{ steps.environment-url.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download k8s namespace
      uses: actions/download-artifact@v2
      with:
        name: namespace-${{ inputs.environment }}.yml

    - name: Download k8s manifests
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.manifestsName && inputs.manifestsName || 'manifests' }}-${{ inputs.environment }}.yml

    - name: Get namespace name
      uses: mikefarah/yq@v4.13.4
      id: namespace
      with:
        cmd: yq eval '.metadata.name' namespace-${{ inputs.environment }}.yml
        
    - name: Get project and namespace names
      shell: bash
      run: |
        if test -f ".github/${{ inputs.environment }}.env"; then
          cat ".github/${{ inputs.environment }}.env" >> $GITHUB_ENV
        fi
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "namespace=${NAMESPACE}" >> $GITHUB_ENV
      env:
        NAMESPACE: ${{ steps.namespace.outputs.result }}

    - name: Define environment URL
      id: environment-url
      shell: bash
      run: |
        HOST=$(cat manifests-${{ inputs.environment }}.yml | yq eval-all '.spec.rules[] .host' -)
        ONE_LINE_HOST=$(echo $HOST | xargs echo -n)
        echo $ONE_LINE_HOST
        echo "::set-output name=url::$ONE_LINE_HOST"

    - name: Format the URL
      uses: actions/github-script@v5
      id: array-url
      env:
        url: ${{ steps.environment-url.outputs.url }}
      with:
        script: |
          const urlArray = JSON.stringify(process.env.url.split(" --- ").map(v => v.replace(/ /g, "")).map(v => `https://${v}`));
          process.stdout.write(`::set-output name=url::${urlArray}`);

    - name: Notify deployment start
      uses: maxgfr/github-multi-deployments@v1.3.2
      id: deployment
      with:
        step: start
        token: ${{ inputs.token }}
        desc: "Deploying environment: ${{ env.namespace }}"
        env: ${{ steps.array-url.outputs.url }}
        debug: true

    - name: Install Kapp
      uses: vmware-tanzu/carvel-setup-action@v1
      with:
        only: kapp
        token: ${{ inputs.token }}

    - name: Create kubernetes config
      shell: bash
      run: |
        mkdir ~/.kube
        touch ~/.kube/config
        echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config
        
    - name: Create k8s namespace
      shell: bash
      run: |
        kubectl create -f namespace-${ENVIRONMENT}.yml || true
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    - name: Deploy application
      shell: bash
      run: |
        sleep 3
        kapp --dangerous-override-ownership-of-existing-resources -y deploy -a ${{ env.project }} --namespace ${{ env.namespace }} -f manifests-${{ inputs.environment }}.yml
    
    - name: Notify deployment
      uses: maxgfr/github-multi-deployments@v1.3.2
      with:
        step: finish
        status: ${{ job.status }}
        token: ${{ inputs.token }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        debug: true
        
    - name: Debug manifests
      uses: socialgouv/actions/k8s-manifests-debug@v1
      with:
        token: ${{ inputs.token }}
        path: manifests-${{ inputs.environment }}.yml
      env:
        RANCHER_PROJECT_ID: ${{ inputs.rancherId }}
