apiVersion: v1
kind: Service
metadata:
  labels:
    component: app
    application: {{ .Values.global.repositoryName }}
  name: app
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    component: app
  type: ClusterIP