name: "Drop database"
description: "Drop database and user"
inputs:
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  adminPgSecret:
    description: "PG Secret admin secretRefName"
  pgUserAddHostSuffix:
    description: "Add user suffix `@hostname`, muste be true for Azure, false for Scaleway, if not provided it autodetect azure using PGHOST"
  projectName:
    description: "Override project name"
  rancherProjectName:
    description: "The Rancher project name, usually secrets.RANCHER_PROJECT_NAME, usefull jobs that needs secrets or ci namespaces"

runs:
  using: "composite"
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup global env vars
      uses: SocialGouv/actions/util-env@v1
      with:
        projectName: ${{ inputs.projectName }}
        rancherProjectName: ${{ inputs.rancherProjectName }}
    
    - name: Setup action bin PATH
      shell: bash
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH

    - name: Setup action's env vars
      shell: bash
      run: |     
        ADMIN_PG_SECRET="${{ inputs.adminPgSecret || env.ADMIN_PG_SECRET || 'azure-pg-admin-user' }}"
        
        PG_USER_ADD_HOST_SUFFIX=${{ inputs.pgUserAddHostSuffix || env.PG_USER_ADD_HOST_SUFFIX }}
        if [ "$PG_USER_ADD_HOST_SUFFIX" != "false" ] && [[ $PGHOST == *"azure.com"* ]]; then
          PG_USER_ADD_HOST_SUFFIX="true"
        fi
        if [ "$PG_USER_ADD_HOST_SUFFIX" ] && [ "$PG_USER_ADD_HOST_SUFFIX" != "false" ]; then
          PGUSER_SUFFIX="@${PGHOST}"
        else
          PGUSER_SUFFIX=""
        fi
        if [ "$SOCIALGOUV_PRODUCTION" ]; then
          DB_NAME=$SOCIALGOUV_PRODUCTION_NAMESPACE
          DB_USER=$SOCIALGOUV_PRODUCTION_NAMESPACE
        elif [ "$SOCIALGOUV_PREPRODUCTION" ]; then
          DB_NAME="preprod"
          DB_USER="preprod${PGUSER_SUFFIX}"
        else
          DB_NAME="autodevops_${BRANCH_SLUG}"
          DB_USER="user_${BRANCH_SLUG}${PGUSER_SUFFIX}"
        fi

        echo "ADMIN_PG_SECRET=$ADMIN_PG_SECRET" >> $GITHUB_ENV
        echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
        echo "DB_USER=$DB_USER" >> $GITHUB_ENV

    - name: Write kubeconfig
      uses: SocialGouv/actions/util-write-kubeconfig@v1
      with:
        kubeconfig: ${{ inputs.kubeconfig }}
      
    - uses: SocialGouv/actions/util-setup-node@v1
      with:
        actionPath: ${{ github.action_path }}
    
    - uses: SocialGouv/actions/util-run-job@v1
      with:
        jobNamespace: ${{ env.JOB_NAMESPACE }}
        jobName: drop-db-${{ env.BRANCH_SLUG }}
        actionPath: ${{ github.action_path }}
        jobTemplatePath: ${{ github.action_path }}/templates/job.drop-db.gtpl

    - name: Wait for drop-db job completion
      uses: SocialGouv/actions/util-wait-job@v1
      with:
        jobNamespace: ${{ env.JOB_NAMESPACE }}
        jobName: drop-db-${{ env.BRANCH_SLUG }}
