apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    component: {{ .Chart.Name }}
    application: {{ .Values.global.repositoryName }}
  name: hasura
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
    - host: >-
        {{ .Values.hostPrefix }}{{ if .Values.host }}{{ .Values.host }}{{ else }}{{ .Values.global.host }}{{ end }}
      http:
        paths:
          - backend:
              service:
                name: hasura
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - >-
          {{ .Values.hostPrefix }}{{ if .Values.host }}{{ .Values.host }}{{ else }}{{ .Values.global.host }}{{ end }}
      secretName: {{ if .Values.certSecretName }}{{ .Values.certSecretName }}{{ else }}{{ .Values.global.certSecretName }}{{ end }}
