apiVersion: v1
kind: Service
metadata:
  labels:
    component: hasura
    application: {{ .Values.global.repositoryName }}
  name: hasura
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    component: hasura
  type: ClusterIP