apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{ .Chart.Name }}
    application: {{ .Values.global.repositoryName }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    component: {{ .Chart.Name }}
  type: ClusterIP