- op: add
  path: "/metadata/annotations"
  value:
    kapp.k14s.io/disable-default-ownership-label-rules: ""
    kapp.k14s.io/disable-default-label-scoping-rules: ""
    kapp.k14s.io/delete-strategy: orphan
