
name: Test autodevops-job

on:
  workflow_dispatch:
  push:
    paths:
      - 'autodevops-job/**'
  pull_request:
    paths:
      - 'autodevops-job/**'
      
jobs:
  autodevops-job:
    runs-on: ubuntu-latest
    name: k8s-manifests-debug tests
    steps:
      - uses: actions/checkout@v2
      
      - run: |
         ls
         mkdir -p ${{ github.workspace }}/.socialgouv
         echo '{"name": "example", "type": "app", "restoreDb": true}' > ${{ github.workspace }}/.socialgouv/config.json

      - id: autodevops-job
        uses: ./autodevops-job
        with: 
          environment: dev
          kube-config: blablabla
          rancherId: some-project-id
          socialgouvBaseDomain: test
          kosko-args: jobs/drop-db
          
      - run: |
          ls
