name: 'build-test'

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: yarn --cwd ./containers-cleaner --frozen-lockfile --prefer-offline

    - run: INPUT_TOKEN=${{ github.token }} yarn --cwd ./containers-cleaner all

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ./containers-cleaner/
      with:
        token: ${{ github.token }}
        retention-weeks: '2'
        containers: |
          fabrique/standup
