namespace: 
host: 
image: 
imagePackage: hasura
imageTag: 
ttl: 
rancherProjectId: my-cluser-id:my-project-id
gitBranch: my-awesome-branch
isProduction: false
isPreProduction: false
replicas: 1
containerPort: 8080
envFrom: []
envConfigName: 
probesPath: /healthz
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscale:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  averageUtilization:
    cpu: 100
    memory: 100
certSecretName: 
hostPrefix: hasura-